---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deluge
  name: deluge
  namespace: torrents
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deluge
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deluge
    spec:
      containers:
        - image: linuxserver/deluge
          name: deluge
          resources: {}
status: {}
