apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-creds
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCSNoxHbzi8j29VTsd8xlAm/QL3zY2d1EAJRJzNCfo8xu+/ltLD+wKycGQ29kZqMxJqw+aBRBTkWY1vryESBNIEWxuF7I9Twad80jbJ2GEcjvYRkH7ZgXVN0JpMvxDHleZaCZxNM8YNoY/qOLi7Kv0CFp67+aDgtGN6kvDx5bigrwWkRgpO4rm2LoVec+qtOjnAQHBRpqfcp1XmCotxC2NF6EjaXkrtHSlp3Cb4Mtse/ogbFYyLRp5WTKRXsffEv8LeyMQhYZpDMaXoIWnFqW6I/pMM02pYBXQNwT4Z2yYQPUp7ycZbDGemyIjGJi6bSA4n4EfhJPJLFfARQYE8/RL77JPwf5x+x129o+485kLjv8PsYB+B9mrC6ooxShcHOYqKTlxGOIcICaYcGxZicGx7ncbDgCv5jbsrvZEcDHND8Ro6STcRRpeIcWZ4WQ60z36/P0PJ8EuURotPRdTnmi+kJH8LYCt/dZICcJIWr3OtS1bVUTz5aLmDl9UCeHumCvEotlX0Hd46UZpCVXW0qVSZaE5NqQ2pc/FOIvLkfJpFeHsIXl+GGN4v1AwrLqqpGxHV9vyhK4WJ6SBI6+GF2Zt7CQpcdrYOysKfTxS4HKtSOJHg4J0scEFD1kHQMPM4MWgnKRBOxII4O3oqDXY+GF4r/cTi4NiyyG8zsYzqGnxOSXjZ+K9rhj+OtqsBtTjzGFaLP1I/B6WkDyhXb6zQjjqbzQcQAQ==
    admin-user: AgCQrX++54BCZT+Nw+1FlQuy2RPNjUdcRcs6MqrmNf56pKlxz/fVL50Le6m8BVv4dPQiK5AmT+v0+5y240pu7jnfNQniR/rDy84YYZheJN7bjyC3opMj/+dEZtPAHA5gO0KpMQWNmo9LLkf1kE9z0zVYGgjHWPLdvxP/uV2lBqZQq/ffvm6pvXoRSePmv/toKBqD3TRPeLV5kaj+B9EMQJz0S6/Vuo/DqLPhqsTfJgDG+0ivjYtj5QAhfNcHfFMJ6k+9hpNyYmZWmYVRvzrU+P1XNxO8H717IGnLUYqt6TjSU8VSzYqPbieO+HGIDsixsdckaXFcKofVMNE0jNwFNkiVIYCvqy/KGywnKrLn0/1bK+3JakJb82CNeeiV/mHGFAVOD4w67gp8pzyUm45qudOpu0S3VdfpHXrcmAG40rLy7ZpP5KQp/kw9c62kaQgkEEeARd2m8EnDQBSOcQgnzovaZtuRiORsj2rFJ6m8BogoiBQHne4/FmCfwolzhFbcOfOc3wAlwN/zXriIFDcbFJj2R0D/s9Az8kk/hMmP6ttaG22QQqQFTuw0XjMozIQfUpnFTUYUrRV4v/AnNcvn5mL0hjX2P0SyV954I+q3JgjnMnIUniHDxrA4AzQmWutzLRes0rhzu4VMaX8ZcctPa8kPRfL/HcT+NA0H5QUwXi8+vBG7GqoM6Pmu4Oaj3bj30XoE5i3S
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-creds
      namespace: monitoring
