image:
  repository: raspbernetes/helm-operator
  tag: v1.2.0
createCRD: true
git:
  ssh:
    secretName: flux-git-deploy
chartsSyncInterval: '10m'
statusUpdateInterval: '10m'
helm:
  versions: 'v3'
prometheus:
  enabled: false
  serviceMonitor:
    create: true
    interval: 30s
    scrapeTimeout: 10s
    namespace: flux
dashboards:
  enabled: false
