---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: rook-ceph
  annotations:
    fluxcd.io/ignore: 'false'
    fluxcd.io/automated: 'false'
spec:
  releaseName: rook-ceph-11
  chart:
    repository: https://charts.rook.io/release
    name: rook-ceph
    version: v1.4.1
  values:
    csi:
      kubeletDirPath: /var/lib/kubelet
      cephcsi:
        image: raspbernetes/ceph-csi:v3.1.0
      registrar:
        image: raspbernetes/csi-node-driver-registrar:2.0.0
      provisioner:
        image: raspbernetes/csi-external-provisioner:2.0.0
      snapshotter:
        image: raspbernetes/csi-external-snapshotter:2.1.1
      attacher:
        image: raspbernetes/csi-external-attacher:3.0.0
      resizer:
        image: raspbernetes/csi-external-resizer:0.5.0
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 1000Mi
