---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 2Ti
