# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: longhorn-dashboard
#   namespace: longhorn-system
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
# spec:
#   ingressClassName: nginx
#   rules:
#     - host: longhorn.internal.home.alan-jenkins.com
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               serviceName: longhorn-frontend
#               servicePort: 80
