---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddns-route53
  namespace: networking
spec:
  metadata:
    name: ddns-route53
    namespace: networking
  template:
    spec:
      containers:
        - image: crazymax/ddns-route53:2.1.0
          envFrom:
            secretRef:
              name: ddns-route53-config
