---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddns-route53
  namespace: networking
spec:
  selector:
    matchLabels:
      app: ddns-route53
  template:
    metadata:
      labels:
        app: ddns-route53
    spec:
      containers:
        - name: ddns-route53
          image: crazymax/ddns-route53:2.1.0
          envFrom:
            - secretRef:
                name: ddns-route53-config
