---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
  annotations:
    flucd.io/automated: 'true'
    fluxcd.io/tag.chart-image: semver:~v0.3
spec:
  releaseName: metrics-server
  helmVersion: v3
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: metrics-server
    version: 2.11.2
  values:
    image:
      repository: k8s.grc.io/k8s-staging-metrics-server/metrics-server
      tag: v0.3.6
