---
apiVersion: helm.flux.cd/v1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: kube-system
  annotations:
    fluxcd.io/automated: 'true'
    fluxcd.io/tag.chart-image: semver:~v0.10
spec:
  releaseName: sealed-secrets
  helmVersion: v3
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: sealed-secrets
    version: 1.10.3
  values:
    image:
      repository: raspbernetes/sealed-secrets
      tag: v0.10.0
