apiVersion: nfs.rook.io/v1alpha1
kind: NFSServer
metadata:
  name: storage
  namespace: storage
spec:
  replicas: 3
  exports:
    - name: storage
      server:
        accessMode: ReadWrite
        squash: none
      persistentVolumeClaim:
        claimName: storage-pvc
  # A key/value list of annotations
  annotations:
  #  key: value
