helmOperator:
  create: true
git:
  url: 'git@github.com:alanjjenkins/k8s-gitops.git'
image:
  repository: raspbernetes/flux
  tag: 1.20.2
registry:
  rps: 50
  burst: 50
memcached:
  tolerations:
    - key: 'arm'
      operator: 'Exists'
prometheus:
  enabled: false
  serviceMonitor:
    create: true
    interval: 30s
    scrapeTimeout: 10s
    namespace: flux
syncGarbageCollection:
  enabled: true
  dry: false
dashboards:
  enabled: false
