---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: networking
  annotations:
    fluxcd.io/ignore: 'false'
    fluxcd.io/automated: 'false'
    fluxcd.io/tag.chart-image: semver:~v0.7
spec:
  releaseName: external-dns
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: external-dns
    version: 3.3.0
  values:
    aws:
      zoneType: public
    image:
      registry: docker.io
      repository: raspbernetes/external-dns
      tag: v0.7.3
      pullPolicy: IfNotPresent
    provider: aws
    policy: upsert-only
    registry: 'txt'
    replicas: 1
    logLevel: debug
    rbac:
      create: true
      pspEnabled: true
    metrics:
      enabled: true
      serviceMonitor:
        enabled: false
        namespace: monitoring
    crd:
      create: true
    sources:
      - service
      - ingress
      - istio-gateway
      - istio-virtualservice
    domainFilters:
      - home.alan-jenkins.com
    extraEnv:
      - name: AWS_IAM_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: external-dns-auth
            key: AWS_IAM_ACCESS_KEY_ID
            optional: false
      - name: AWS_IAM_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: external-dns-auth
            key: AWS_IAM_SECRET_ACCESS_KEY
            optional: false
      - name: AWS_DEFAULT_REGION
        valueFrom:
          secretKeyRef:
            name: external-dns-auth
            key: AWS_DEFAULT_REGION
            optional: false
